matrix:
  include:

    - language: node_js
      node_js:
        - "node"
        - "iojs"
      before_script:
        - cd frontend
      install:
        - npm install -g codecov
      script:
        - npm install
        - npm run build
       # - npm run test:unit
        - codecov

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: 7632a8645eec40303dfb5b7abd5a70ec983c84e1
        keep-history: true
        verbose: true
        on:
          branch: master

      before_deploy:
        - zip -r deploy.zip package.json src/ public/

      after_deploy:
        - unzip -l deploy.zip 
